### ISSUE TITLE
Migrate FLIP code to AI4VBH FLIP repo for public release

### ISSUE THREAD

**Issue by heyhaleema** [AI4VBH/FLIP#4]
See #3 for discussion.

**Comment by heyhaleema** [comment]
@jonanswer Could you list out all the FLIP repos to be migrated (if not already) as a checklist in a following comment? Once they've all be checked, I think we can close this issue.

**Comment by jonanswer** [comment]
@heyhaleema , as we are in the last week of development, it would be safer to migrate the repos next week once there is just a skeleton staff in - new development will be limited so the risks will be lower. The repos to be migrated are:

AnswerConsulting/flip-hub-api -> AI4VBH/FLIP-central-hub-api
AnswerConsulting/flip-hub-fl_wrapper -> AI4VBH/FLIP-central-hub-fl-wrapper
AnswerConsulting/flip-trust-api -> AI4VBH/FLIP-trust-api
AnswerConsulting/flip-trust-data-access-api -> AI4VBH/FLIP-trust-data-access-api
AnswerConsulting/flip-trust-data-import-api -> AI4VBH/FLIP-trust-data-import-api
AnswerConsulting/flip-trust-imaging-api -> AI4VBH/FLIP-trust-imaging-api
AnswerConsulting/flip-fl-base-application -> AI4VBH/FLIP-fl-base-application
AnswerConsulting/flip-trust-fl-client -> AI4VBH/FLIP-trust-fl-client
AnswerConsulting/flip-sample-application -> AI4VBH/FLIP-sample-application
AnswerConsulting/flip-ui -> AI4VBH/FLIP-ui
AnswerConsulting/flip-utils -> AI4VBH/FLIP-utils
AnswerConsulting/flip-api-tests -> AI4VBH/FLIP-api-tests

Once all repos are migrated, we'll run test builds and smoke tests to make sure all is transferred correctly.

**Comment by heyhaleema** [comment]
@handyandypandyandy @carlsmith-ad @Dusty-Meg Following up on Jon's last comment, have all the FLIP repos been migrated to the AI4VBH organisation?

@mjorgecardoso @Jaws785 If so, I suggest this issue be closed.

**Comment by Dusty-Meg** [comment]
@heyhaleema All FLIP specific repositories have been migrated to the AI4VBH organisation.
